<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $commercialDisplays = Category::where('name', 'Commercial Displays')->first();
        $kiosks = Category::where('name', 'Kiosks')->first();
        $activeLed = Category::where('name', 'Active LED Al diecast')->first();
        $cabinets = Category::where('name', 'Cabinets')->first();
        $mediaPlayers = Category::where('name', 'Media Players')->first();
        $controllers = Category::where('name', 'Controllers')->first();

        $products = [
            // Commercial Displays
            [
                'category_id' => $commercialDisplays->id,
                'name' => 'LG 43" DISPLAYS',
                'sku' => 'LG43UL3J',
                'hsn_code' => '85285900',
                'brand' => 'LG',
                'type' => 'Commercial Display',
                'gst_percentage' => 28,
                'price' => 45000,
                'price_per_sqft' => 0,
                'min_price' => 42000,
                'max_price' => 48000,
                'description' => '43-inch commercial display with high brightness and durability',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $commercialDisplays->id,
                'name' => 'LG 49" VIDEO WALL',
                'sku' => '49VL7D',
                'hsn_code' => '85285900',
                'brand' => 'LG',
                'type' => 'Commercial Display',
                'gst_percentage' => 28,
                'price' => 65000,
                'price_per_sqft' => 0,
                'min_price' => 60000,
                'max_price' => 70000,
                'description' => '49-inch video wall display with ultra-narrow bezel',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $commercialDisplays->id,
                'name' => 'LG 55" VIDEO WALL',
                'sku' => '55VL7D',
                'hsn_code' => '85285900',
                'brand' => 'LG',
                'type' => 'Commercial Display',
                'gst_percentage' => 28,
                'price' => 75000,
                'price_per_sqft' => 0,
                'min_price' => 70000,
                'max_price' => 80000,
                'description' => '55-inch video wall display with high resolution',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $commercialDisplays->id,
                'name' => 'LG 65" VIDEO WALL',
                'sku' => '65VL7D',
                'hsn_code' => '85285900',
                'brand' => 'LG',
                'type' => 'Commercial Display',
                'gst_percentage' => 28,
                'price' => 95000,
                'price_per_sqft' => 0,
                'min_price' => 90000,
                'max_price' => 100000,
                'description' => '65-inch video wall display with 4K resolution',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $commercialDisplays->id,
                'name' => 'LG 75" VIDEO WALL',
                'sku' => '75VL7D',
                'hsn_code' => '85285900',
                'brand' => 'LG',
                'type' => 'Commercial Display',
                'gst_percentage' => 28,
                'price' => 125000,
                'price_per_sqft' => 0,
                'min_price' => 120000,
                'max_price' => 130000,
                'description' => '75-inch video wall display with ultra HD resolution',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $commercialDisplays->id,
                'name' => 'LG 86" VIDEO WALL',
                'sku' => '86VL7D',
                'hsn_code' => '85285900',
                'brand' => 'LG',
                'type' => 'Commercial Display',
                'gst_percentage' => 28,
                'price' => 185000,
                'price_per_sqft' => 0,
                'min_price' => 180000,
                'max_price' => 190000,
                'description' => '86-inch video wall display with 4K resolution',
                'status' => 'active',
                'unit' => 'INR',
            ],

            // Kiosks
            [
                'category_id' => $kiosks->id,
                'name' => 'A FRAME STANDEE 43"',
                'sku' => 'AFS43BLK',
                'hsn_code' => '732690',
                'brand' => 'Radiant Synage',
                'type' => 'KIOSK',
                'gst_percentage' => 18,
                'price' => 15000,
                'price_per_sqft' => 0,
                'min_price' => 14000,
                'max_price' => 16000,
                'description' => '43-inch A-frame standee with black finish',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $kiosks->id,
                'name' => 'A FRAME STANDEE 55"',
                'sku' => 'AFS55BLK',
                'hsn_code' => '732690',
                'brand' => 'Radiant Synage',
                'type' => 'KIOSK',
                'gst_percentage' => 18,
                'price' => 20000,
                'price_per_sqft' => 0,
                'min_price' => 19000,
                'max_price' => 21000,
                'description' => '55-inch A-frame standee with black finish',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $kiosks->id,
                'name' => 'A FRAME STANDEE 65"',
                'sku' => 'AFS65BLK',
                'hsn_code' => '732690',
                'brand' => 'Radiant Synage',
                'type' => 'KIOSK',
                'gst_percentage' => 18,
                'price' => 25000,
                'price_per_sqft' => 0,
                'min_price' => 24000,
                'max_price' => 26000,
                'description' => '65-inch A-frame standee with black finish',
                'status' => 'active',
                'unit' => 'INR',
            ],

            // Active LED Al diecast
            [
                'category_id' => $activeLed->id,
                'name' => 'Unilumin Kslim 1.9',
                'sku' => 'UNI-KSLIM-1.9',
                'hsn_code' => '85285900',
                'brand' => 'Unilumin',
                'type' => 'Active LED Al diecast',
                'gst_percentage' => 28,
                'price' => 35000,
                'price_per_sqft' => 3500,
                'min_price' => 33000,
                'max_price' => 37000,
                'description' => '1.9mm pixel pitch LED display with slim design',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $activeLed->id,
                'name' => 'Unilumin Kslim 2.5',
                'sku' => 'UNI-KSLIM-2.5',
                'hsn_code' => '85285900',
                'brand' => 'Unilumin',
                'type' => 'Active LED Al diecast',
                'gst_percentage' => 28,
                'price' => 30000,
                'price_per_sqft' => 3000,
                'min_price' => 28000,
                'max_price' => 32000,
                'description' => '2.5mm pixel pitch LED display with slim design',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $activeLed->id,
                'name' => 'Unilumin Kslim 2.9',
                'sku' => 'UNI-KSLIM-2.9',
                'hsn_code' => '85285900',
                'brand' => 'Unilumin',
                'type' => 'Active LED Al diecast',
                'gst_percentage' => 28,
                'price' => 28000,
                'price_per_sqft' => 2800,
                'min_price' => 26000,
                'max_price' => 30000,
                'description' => '2.9mm pixel pitch LED display with slim design',
                'status' => 'active',
                'unit' => 'INR',
            ],

            // Cabinets
            [
                'category_id' => $cabinets->id,
                'name' => 'MS CABINETS OUTDOOR',
                'sku' => 'CAB-OD-01',
                'hsn_code' => '85299090',
                'brand' => '',
                'type' => 'Cabinets',
                'gst_percentage' => 18,
                'price' => 20000,
                'price_per_sqft' => 0,
                'min_price' => 19000,
                'max_price' => 21000,
                'description' => 'Outdoor media server cabinet with weather protection',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $cabinets->id,
                'name' => 'MS CABINETS INDOOR',
                'sku' => 'CAB-ID-01',
                'hsn_code' => '85299090',
                'brand' => '',
                'type' => 'Cabinets',
                'gst_percentage' => 18,
                'price' => 15000,
                'price_per_sqft' => 0,
                'min_price' => 14000,
                'max_price' => 16000,
                'description' => 'Indoor media server cabinet with ventilation',
                'status' => 'active',
                'unit' => 'INR',
            ],

            // Media Players
            [
                'category_id' => $mediaPlayers->id,
                'name' => 'ANDROID MEDIA PLAYER LN',
                'sku' => 'MP-AND-4G32G',
                'hsn_code' => '84715000',
                'brand' => '',
                'type' => 'Media Player',
                'gst_percentage' => 18,
                'price' => 12000,
                'price_per_sqft' => 0,
                'min_price' => 11000,
                'max_price' => 13000,
                'description' => 'Android media player with 4GB RAM and 32GB storage',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $mediaPlayers->id,
                'name' => 'ANDROID MEDIA PLAYER HN',
                'sku' => 'MP-AND-8G64G',
                'hsn_code' => '84715000',
                'brand' => '',
                'type' => 'Media Player',
                'gst_percentage' => 18,
                'price' => 18000,
                'price_per_sqft' => 0,
                'min_price' => 17000,
                'max_price' => 19000,
                'description' => 'High-end Android media player with 8GB RAM and 64GB storage',
                'status' => 'active',
                'unit' => 'INR',
            ],

            // Controllers
            [
                'category_id' => $controllers->id,
                'name' => 'LED Controller Media Players',
                'sku' => 'CTRL-NOV-TB2',
                'hsn_code' => '85437049',
                'brand' => 'Novastar',
                'type' => 'Controllers',
                'gst_percentage' => 18,
                'price' => 8000,
                'price_per_sqft' => 0,
                'min_price' => 7500,
                'max_price' => 8500,
                'description' => 'LED controller for media players with advanced features',
                'status' => 'active',
                'unit' => 'INR',
            ],
            [
                'category_id' => $controllers->id,
                'name' => 'LED Controller Media Players',
                'sku' => 'CTRL-NOV-TB3',
                'hsn_code' => '85437049',
                'brand' => 'Novastar',
                'type' => 'Controllers',
                'gst_percentage' => 18,
                'price' => 10000,
                'price_per_sqft' => 0,
                'min_price' => 9500,
                'max_price' => 10500,
                'description' => 'Advanced LED controller for media players',
                'status' => 'active',
                'unit' => 'INR',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
